server:  port: 9080
spring:  kafka:    producer:      bootstrap-servers: ${bootstrap-servers:localhost:9095,localhost:9096,localhost:9097}      key-serializer: ${key-serializer:org.apache.kafka.common.serialization.StringSerializer}      value-serializer: ${value-serializer:org.springframework.kafka.support.serializer.JsonSerializer}      ssl:        trust-store-location: file:src/main/resources/client.truststore.jks        trust-store-password: ${ trust-store-password:password}        key-store-location: file:src/main/resources/client.keystore.jks        key-store-password:  ${key-store-password:password}      properties:        acks: 1        retries: 10        retry.backoff.ms: 1000        security:          protocol: SSL        ssl.endpoint.identification.algorithm:        
kafka:
  topic:  GC-Test
  groupId: test-group
  accounts:
    topic: account-update
